title: C:\dev\mss_debug\Integrative Modelling Platform Project9\Integrative Modelling Platform Experiment
date: 2019-06-16T12:44:14.5504681-06:00
states: 1
sampling_frame: 150
output_dir: ./imp_output
data_directory: ../
topology_file: Topology.txt
target_gmm_file: gmm_file_ouput.txt
cores: 2 
replicates: 3
crosslinkdb:
- refid: PRC2_BS3.csv
- refid: PRC2_DSS.csv
xl_groupA:
- refid: PRC2_BS3.csv
  length: 21.0
  slope: 0.01
  resolution: 1.0
  label: PRC2_BS3
  weight: 1.0
  crosslink_distance: 30.0
- refid: PRC2_DSS.csv
  length: 21.0
  slope: 0.01
  resolution: 1.0
  label: PRC2_DSS
  weight: 1.0
  crosslink_distance: 30.0
xl_dbA:
- refid: PRC2_BS3.csv
  set_protein1_key: Protein 1
  set_protein2_key: Protein 2
  set_site_pairs_key: Selected Sites
  set_unique_id_key: Peptide ID
- refid: PRC2_DSS.csv
  set_protein1_key: Protein 1
  set_protein2_key: Protein 2
  set_site_pairs_key: Selected Sites
  set_unique_id_key: Peptide ID
degree_of_freedom:
  max_rb_trans: 4.0
  max_rb_rot: 0.3
  max_bead_trans: 4.0
  max_srb_trans: 4.0
  max_srb_rot: 0.3

